adamhathcock/sharpcompress

SharpCompress/Common/SevenZip/ArchiveReader.cs
SharpCompress/Common/Tar/Headers/TarHeader.cs
SharpCompress/Utility.cs

Currently, not all archive types return the modification time of entry in the same format. ZIP returns the time in local time, while TAR and 7Z returns UTC time.
This has caused that in my timezone the modification time for .zip entries were correct, while the ones for .tar and .7z entries were 1 hour off.
I have fixed it, so that now every archive returns time as local time.
I was not sure whether it's better to always return local or UTC time, but I have decided to return local time as it is a bit more intuitive for a user. In the long term, it does not matter, as there is conversion available between them with the usage of .ToLocalTime() and ToUniversalTime() .methods, what matters is that returned times have to be consistent for all supported formats.

Inconsistent time format

---

SharpCompress/Archive/GZip/GZipWritableArchiveEntry.cs
SharpCompress/Archive/Rar/RarArchiveEntry.cs
SharpCompress/Archive/Tar/TarWritableArchiveEntry.cs
SharpCompress/Archive/Zip/ZipWritableArchiveEntry.cs
SharpCompress/AssemblyInfo.cs
SharpCompress/Common/Entry.cs
SharpCompress/Common/GZip/GZipEntry.cs
SharpCompress/Common/IEntry.cs
SharpCompress/Common/Rar/RarEntry.cs
SharpCompress/Common/SevenZip/SevenZipEntry.cs
SharpCompress/Common/Tar/TarEntry.cs
SharpCompress/Common/Zip/ZipEntry.cs

Added attribute [assembly: CLSCompliant(true)] and changed type of
public Crc properties from uint to long to satisfy CLS compliance.

Made the assembly CLSCompliant.

---

SharpCompress/SharpCompress.NET2.csproj

Fixed typo and include missing files into NET2 project.

fixed: .NET2 project is not compiling

---

SharpCompress.Test/Tar/TarArchiveTests.cs
SharpCompress/Common/Tar/Headers/TarHeader.cs

Support for writing arbitrarily long filenames in tar archives.
The existing code used the ustar prefix field for supporting filepaths up to 255 chars (the actual maximum filepath length depends on the exact location of the slashes in the pat). However, there was a bug (several bugs, in fact) in the implementation that caused the filewriter to throw an error when a filepath of > 100 chars was used.
This pull request drops the use of the ustar prefix field in favor of the use of LongLinks. As far as I can tell, the use of LongLink is more common than the use of the ustar prefix field. Both 7zip and gnu tar use LongLinks by default. 
Since the previous implementation never worked anyway, there are no users depending on the use of the ustar prefix field.

Tar long name support

---

SharpCompress/Writer/Tar/TarWriter.cs

Commit d36ae445e29de46879bfb23299ad8fa9ea59d4b1 caused tar.bz2 file generation and the Tar_BZip2_Writer test to fail. This reverts that commit.

Fixed bug where tar.bz2 compression did not work

---

SharpCompress/SharpCompress.NET2.csproj

The .NET2 project only built in Debug configuration due to not including
the compilation symbol NET2 in the Release configuration.

Fixed .NET2 Release build

---

SharpCompress/Common/Rar/Headers/ProtectHeader.cs
SharpCompress/Common/Rar/Headers/RarHeaderFactory.cs
SharpCompress/SharpCompress.NET2.csproj
SharpCompress/SharpCompress.Portable.csproj
SharpCompress/SharpCompress.PortableTest.csproj
SharpCompress/SharpCompress.WindowsStore.csproj
SharpCompress/SharpCompress.csproj

Some RARs with recovery records contain Protect Headers, I've added
support for parsing them so that RARs containing them can be read,
instead of an invalid-header exception being thrown. Parsing logic taken
from unrar reference source.

Added read support for RARs with Protect Headers

---

SharpCompress/Writer/Zip/ZipWriter.cs

ShaprCompress is used internally in Mono to implement
System.IO.Compression, which allows the user to specify path encoding.
The change allows for specifying the encoding via
ArchiveEncoding.Default.

ZipWriter: use ArchiveEncoding.Default

---

SharpCompress/Archive/SevenZip/SevenZipArchive.cs
SharpCompress/Common/EntryStream.cs
SharpCompress/Reader/AbstractReader.cs
SharpCompress/Reader/IReader.cs
SharpCompress/Reader/Rar/RarReader.cs

Until now the caller had to completely consume each entry stream, or call SkipEntry(), before disposing the stream. If not, exception was thrown: "EntryStream has not been fully consumed". Hugely inconvenient; a user-thrown exception inside a "using (EntryStream)" block would be discarded.
Now automatically skips the entry on dispose.
Added method EntryStream.Cancel(). Call this if entry stream is unfinished, and no further entries are required. Helps with efficiency, as it avoids reading data that is not needed.

Skip entry stream on dispose

---

SharpCompress.Test/ArchiveTests.cs
SharpCompress.Test/SevenZip/SevenZipArchiveTests.cs
SharpCompress.Test/TestBase.cs
SharpCompress/Archive/AbstractArchive.cs
SharpCompress/Archive/IArchive.cs
SharpCompress/Archive/IArchiveEntry.Extensions.cs
SharpCompress/Archive/SevenZip/SevenZipArchive.cs
SharpCompress/Common/Entry.cs
SharpCompress/Common/ExtractOptions.cs
SharpCompress/Common/IEntry.cs
SharpCompress/Common/SevenZip/ArchiveReader.cs
SharpCompress/Common/SevenZip/CStreamSwitch.cs
SharpCompress/Common/SevenZip/DataReader.cs
SharpCompress/Common/SevenZip/SevenZipEntry.cs

Fixed TotalSize For 7z
added TotalUncompressSize Tested for 7z
this enables to show progress for the entire archive
Added 2 Extract Options: PreserveFileTime And PreserveAttributes.
Put All the Log Command under DEBUG Condition.

Extract Options And Total Sizes

---

SharpCompress/SharpCompress.Portable.csproj
SharpCompress/SharpCompress.PortableTest.csproj
SharpCompress/SharpCompress.Unsigned.csproj
SharpCompress/SharpCompress.WindowsStore.csproj
SharpCompress/SharpCompress.csproj
SharpCompress/Writer/Zip/ZipCompressionInfo.cs
SharpCompress/Writer/Zip/ZipWriter.cs

We use the ZipWriter to create archive with compression type deflate. But there is a problem - the default Mac UI unzipping (double click on the zip file) is throwing "Unable to expand. Error 2 No such file or directory." if there is an empty file in the archive. It only works  for archives that store the empty files and do not compress them.
As this is not a general bug, but one tool issue, the solution for me is to provide the API with option to explicitly change the compression info for specific files. This way if there are empty files or other specifics one can have different compression infos in one archive.

Add explicit compressioninfo when writing file to zip

---

SharpCompress/Writer/Zip/ZipWriter.cs

The java runtime on Android cannot process file entries with the fixed
version 63 - it can only process entries up to version 20, which should
be fine if the entry was compressed using deflate.

Zip entry header version for Deflate compression set to 20

---

SharpCompress/Compressor/Deflate/DeflateManager.cs

Fixes broken build in VS2013 introduced by
18bd8102281c04c7eb09ecfdd984d7382b629f2c. That commit attempted to fix a
compiler warning from VS2015, but this turns out to be a compiler bug:
https://github.com/dotnet/roslyn/issues/4027 . That commit added code
which VS2013 correctly treats as a compiler warning, breaking the VS2013
build.
I have reverted this unnecessary change to the deflate code, fixing the
VS2013 build, and disabled warning CS0675 on send_bits() which will
satisfy VS2015.
Fixes https://github.com/adamhathcock/sharpcompress/issues/79

Fix VS2013 compiler warnings (errors)

---

SharpCompress/Archive/Zip/ZipArchive.cs
SharpCompress/Common/Zip/StreamingZipHeaderFactory.cs
SharpCompress/Common/Zip/ZipHeaderFactory.cs

Revert commit that caused all non-zip files to be read entirely upon opening.
IsZipArchive() would read and process the entire file looking for a zip header.

Fixed serious performance regression (revert 0f12a073af4486509dfd777da1854efb5dc571ee)

---

SharpCompress/SharpCompress.PortableTest.csproj
SharpCompress/SharpCompress.Unsigned.csproj

Fixes release builds of SharpCompress.Test and SharpCompress.Test.Portable. The UNSIGNED symbol was missing from the Release configurations of SharpCompress.Unsigned and SharpCompress.PortableTest

Fix Release build of Tests

---

SharpCompress/Archive/Rar/RarArchive.cs

When using the following code the program will crash because there is no password specified
```c#
var archive = RarArchive.Open(***);
var entries = archive.ExtractAllEntries();
while(entries.MoveToNextEntry()) { // cryptographic exception here
// do something with entries
}
```
This pull requests passes the password to the `RarReader`

Add password when opening RarReader

---

SharpCompress/Archive/IArchiveEntry.Extensions.cs
SharpCompress/Common/IEntry.Extensions.cs
SharpCompress/Reader/IReader.Extensions.cs
SharpCompress/SharpCompress.PortableTest.csproj
SharpCompress/SharpCompress.Unsigned.csproj
SharpCompress/SharpCompress.csproj

Previously only `IArchive` would use the `ExtractionOptions` enum to set the timestamps & attributes on extracted files. With this change the common logic is extracted out and used during both `IReader` and `IArchive` extraction.

Preserve File Timestamps with IReader

---

SharpCompress/Compressor/Deflate/Inflate.cs

After tracking down a case of a corrupt file being extracted, I was able to isolate the issue to a single 100kb file. If I compress this file with the maximum compression, and decompress it, I the loose the trailing 109 bytes.
I have finally tracked down the issue and made this patch. The problem is that the number of bits requested is larger than the number of bits required. For the `LEN` and `DIST` case, the number of required bits `k`  is set to `lbits` and `dbits` respectively. But if you look in the code below, you can see that they "consume" a variable number of bits, which in this case is less than `k`.
For most cases this is not a problem, but when the last code to be processed hits this case, the decompression stops prematurely and this cuts of a number of bytes. Other zip …

	Bugfix for inflate algorithm cutting of the end of certain blocks

---

SharpCompress/Archive/Rar/FileInfoRarFilePart.cs
SharpCompress/Common/GZip/GZipVolume.cs
SharpCompress/Common/SevenZip/ArchiveReader.cs
SharpCompress/Common/SevenZip/DataReader.cs
SharpCompress/Compressor/LZMA/Bcj2DecoderStream.cs

When building the solution with Xamarin Studio on OSX, it complains about a number of unused fields and variables.
Commenting these out has no ill effect. I can make an update with the fields deleted if you like.

Fix various warnings

---

SharpCompress/Common/GZip/GZipFilePart.cs
SharpCompress/Common/Tar/Headers/TarHeader.cs
SharpCompress/Common/Zip/Headers/ZipFileEntry.cs
SharpCompress/Common/Zip/WinzipAesCryptoStream.Portable.cs
SharpCompress/Common/Zip/WinzipAesCryptoStream.cs
SharpCompress/Common/Zip/WinzipAesEncryptionData.Portable.cs
SharpCompress/Common/Zip/WinzipAesEncryptionData.cs
SharpCompress/Common/Zip/ZipFilePart.cs
SharpCompress/Compressor/Deflate/GZipStream.cs
SharpCompress/Compressor/Deflate/ZlibBaseStream.cs
SharpCompress/Compressor/LZMA/LzmaStream.cs
SharpCompress/Compressor/PPMd/H/FreqData.cs
SharpCompress/Compressor/PPMd/H/PPMContext.cs
SharpCompress/Compressor/PPMd/H/RarMemBlock.cs
SharpCompress/Compressor/PPMd/H/RarNode.cs
SharpCompress/Compressor/PPMd/H/State.cs
SharpCompress/Compressor/PPMd/PpmdProperties.cs
SharpCompress/Compressor/Rar/VM/RarVM.cs
SharpCompress/Converter/DataConverter.Portable.cs
SharpCompress/Converter/DataConverter.cs
SharpCompress/Crypto/PBKDF2.cs
SharpCompress/IO/MarkingBinaryReader.cs
SharpCompress/SharpCompress.Portable.csproj
SharpCompress/SharpCompress.PortableTest.csproj
SharpCompress/SharpCompress.Unsigned.csproj
SharpCompress/SharpCompress.WindowsStore.csproj
SharpCompress/SharpCompress.csproj
SharpCompress/Utility.cs
SharpCompress/Writer/Zip/ZipCentralDirectoryEntry.cs
SharpCompress/Writer/Zip/ZipWriter.cs

SharpCompress can now be used on machines with big endian architecture
such as powerpc. All byte conversions now run through Mono's
DataConverter (or a portable version for builds that don't allow unsafe
code) instead of BitConverter, as BitConverter's behavior depends on the
host cpu.

SharpCompress now endian neutral

---

SharpCompress/Writer/Zip/ZipWriter.cs

This is a fix to:
https://github.com/adamhathcock/sharpcompress/issues/120

Fix setting compressioninfo on Zip streams

---

SharpCompress/Common/Tar/Headers/TarHeader.cs

Fixes https://github.com/adamhathcock/sharpcompress/issues/128

Support tars with global extended headers

---

src/SharpCompress/Compressor/LZMA/DecoderStream.cs
src/SharpCompress/IO/BufferedSubStream.cs

7z archives may require alternating reads from multiple substreams so it is important to seek before reading from the underlying stream. To keep performance at an acceptable level it is necessary to perform buffering because seeking on every single one-byte-read will destroy performance.

Fix for issue #73

---

README.md
src/SharpCompress/Compressors/PPMd/PpmdProperties.cs
src/SharpCompress/Compressors/PPMd/PpmdVersion.cs
src/SharpCompress/Writers/Zip/ZipWriter.cs

Fixes https://github.com/adamhathcock/sharpcompress/issues/182

Make PpmdProperties lazy to avoid unnecessary allocations.

---

src/SharpCompress/Archives/SevenZip/SevenZipArchive.cs
src/SharpCompress/Common/Volume.cs
src/SharpCompress/Readers/AbstractReader.cs
src/SharpCompress/Readers/ReaderFactory.cs
test/SharpCompress.Test/Zip/ZipReaderTests.cs

Fix for https://github.com/adamhathcock/sharpcompress/issues/187

Fix null password on ReaderFactory.  Fix null options on SevenZipArchive

---

src/SharpCompress/Common/Zip/Headers/DirectoryEntryHeader.cs
src/SharpCompress/Common/Zip/Headers/LocalEntryHeader.cs
src/SharpCompress/Common/Zip/Headers/LocalEntryHeaderExtraFactory.cs
src/SharpCompress/Common/Zip/StreamingZipHeaderFactory.cs
src/SharpCompress/Common/Zip/ZipFilePart.cs
test/SharpCompress.Test/Zip/ZipReaderTests.cs

This PR adds support for reading the zip64 extended information field, which wasn't required for my previous test files, but probably is required in general for zip64 archives (the tripping point in my testing was new files starting beyond the 4Gb point of my archive).
Adding this support also instantly fixed the trouble I was having with ZipReader support, so that has been included.

Zip64 extending information and ZipReader

---

src/SharpCompress/Common/Zip/Headers/DirectoryEntryHeader.cs
src/SharpCompress/Common/Zip/Headers/LocalEntryHeader.cs

This fixes a bug introduced with 6be6ef0b5c3ed6a4d40d00c8fb133518e75e4a6f.
Bad news is that all zip files written with 0.15.1 are semi-broken.
That is, their filenames are garbled, but content is recoverable.

Fix invalid headers

---

src/SharpCompress/Common/Rar/Headers/RarHeader.cs
src/SharpCompress/Common/Rar/Headers/RarHeaderFactory.cs
src/SharpCompress/Common/Rar/RarCrcBinaryReader.cs
src/SharpCompress/Common/Rar/RarCryptoBinaryReader.cs
src/SharpCompress/Compressors/Rar/MultiVolumeReadOnlyStream.cs
src/SharpCompress/Compressors/Rar/RarCRC.cs
src/SharpCompress/Compressors/Rar/RarCrcStream.cs
src/SharpCompress/IO/MarkingBinaryReader.cs
src/SharpCompress/Readers/Rar/RarReader.cs

verify rar file crc checksums:
- header records
- decompressed file payload
tested and works with:
- typical rar files
- rar files with encrypted headers
- multipart rar files

verify RAR crc on header and file data

---

src/SharpCompress/Writers/Zip/ZipCentralDirectoryEntry.cs

Sets the default level of '20' for zip files in the ZipCentralDirectoryBlock to match '20' used in Zip Local File Headers at https://github.com/adamhathcock/sharpcompress/blob/master/src/SharpCompress/Writers/Zip/ZipWriter.cs#L162
This makes Microsoft's compression.io library used by NuGet happy (and possibly some other tools)

Default zip ver to 20 (deflate/encyption), fixes #164

---

src/SharpCompress/SharpCompress.csproj

This re-enables WinZipAes support for .NET 3.5.

Fix for Issue #250: remove extra build flags for .NET 3.5

---

src/SharpCompress/Readers/AbstractReader.cs
tests/SharpCompress.Test/Zip/ZipReaderTests.cs

Fixes https://github.com/adamhathcock/sharpcompress/issues/162

Fix Skipping when compressed size is unknown (fallback to decompressing)

---

src/SharpCompress/Common/ArchiveEncoding.cs

A simple usage with [SimpleHelpers.FileEncoding](https://www.nuget.org/packages/SimpleHelpers.FileEncoding/) package (which is a Chardet helper):
```
var f = ArchiveFactory.Open(@"X:\some-really-old.zip", new ReaderOptions
{
ArchiveEncoding = new ArchiveEncoding
{
CustomDecoder = (bytes, start, count) =>
FileEncoding.DetectFileEncoding(bytes, start, count, Encoding.UTF8)
.GetString(bytes, start, count)
}
});
foreach (var entry in f.Entries)
{
Debug.WriteLine(entry.Key);
}
```

Optional string decoder delegate: fix #277

---

src/SharpCompress/Archives/GZip/GZipArchive.cs
src/SharpCompress/Common/GZip/GZipFilePart.cs
src/SharpCompress/Common/Zip/Headers/ZipFileEntry.cs
src/SharpCompress/Common/Zip/StreamingZipFilePart.cs
src/SharpCompress/Common/Zip/WinzipAesCryptoStream.cs
src/SharpCompress/Common/Zip/ZipFilePart.cs
src/SharpCompress/Compressors/Xz/BinaryUtils.cs
src/SharpCompress/Readers/AbstractReader.cs
src/SharpCompress/Utility.cs

Fixes https://github.com/adamhathcock/sharpcompress/issues/275 with some clean up

Use Skip and ReadFully extension methods where possible.

---

src/SharpCompress/Archives/Zip/ZipArchive.cs

This bug causes entry keys in wrong encoding when using ExtractAllEntries/MoveToNextEntry if non-UTF8 encoding specified at ZipArchive.Open

Fixed bug: Passing default ReaderOptions when creating ZipReader for solid extraction

---

src/SharpCompress/Writers/Zip/ZipWriter.cs

https://github.com/adamhathcock/sharpcompress/issues/294

Fixes Double Dispose() of ZipWritingStream #294

---

src/SharpCompress/Compressors/Xz/MultiByteIntegers.cs
tests/SharpCompress.Test/Xz/XZIndexTests.cs

The `ReadXZInteger` extension method reads VLIs in XZ streams. It reads the right number of bytes, but does not return the correct value for multi-byte VLIs (>= 128) because an increment is missing.
This PR adds the missing increment, with a unit test (based on XZIndex). The fix matches the [reference Java implementation](https://git.tukaani.org/?p=xz-java.git;a=blob;f=src/org/tukaani/xz/common/DecoderUtil.java;h=77ba4413e71ef37f73b29d8dca96231c1c75240a;hb=HEAD#l106).
I see two cases where a valid XZ file could previously not be read:
- XZ file with an index containing >= 128 records (AFAIK indexes aren't that common),
- block filter with >= 128 bytes of properties (seems unlikely).

XZ: fix variable-length integers decoding

---

src/SharpCompress/Compressors/Rar/RarCrcStream.cs

eliminate spurious rar crc exception when Read() is called with count = 0

bugfix: eliminate spurious rar crc exception

---

src/SharpCompress/Common/Rar/Headers/MarkHeader.cs

Rar 5 format

---

src/SharpCompress/Utility.cs

Hello.
I have a large zip file.(~100GB 871kEntries)
I tried below code.
```csharp
var sw = Stopwatch.StartNew();
using (var stream = new FileStream(@"large.zip", FileMode.Open, FileAccess.Read, FileShare.Read))
using (var reader = ZipReader.Open(stream, new SharpCompress.Readers.ReaderOptions { LeaveStreamOpen = true }))
{
while (reader.MoveToNextEntry())
{
//Console.WriteLine(reader.Entry.Key);
}
}
Console.WriteLine(sw.Elapsed);
```
It took about 13 minutes in my machine.
However, when this PR is applied, it was shortened to 10 seconds.
Does this cause problems?
I'm sorry for my poor English.
Thank you for reading.

Utility.Skip uses seek

---

src/SharpCompress/Archives/Tar/TarArchive.cs
src/SharpCompress/Writers/Tar/TarWriter.cs
src/SharpCompress/Writers/Tar/TarWriterOptions.cs
src/SharpCompress/Writers/WriterFactory.cs
tests/SharpCompress.Test/Tar/TarWriterTests.cs

I'm not sure if this flag should be included in WriterOptions since no other archives could support it. Moreover zip archive also has finalization logic but there is no sense to leave it open since it is not possible to resume zip archive writing (correct me if I'm wrong and I'll move this flag to WriterOptions).
If there are no objections with this approach - I'll add tests for these changes.
Related to #323

Added ability to leave tar archive open after stream is closed

---

src/SharpCompress/Common/Entry.cs

When inspecting a `TarArchive` under the debugger, I found that all entries are listed as `{SharpCompress.Archives.Tar.TarArchiveEntry}`.
This PR implements `Entry.ToString()` by returning `Entry.Key`, so that each entry now shows up with its actual file name.
Could be useful for logging/monitoring scenarios as well.

Implement Entry.ToString()

---

src/SharpCompress/Common/EntryStream.cs
src/SharpCompress/Common/Tar/TarReadOnlySubStream.cs
src/SharpCompress/Compressors/BZip2/BZip2Stream.cs
src/SharpCompress/Compressors/BZip2/CBZip2InputStream.cs
src/SharpCompress/Compressors/BZip2/CBZip2OutputStream.cs
src/SharpCompress/Compressors/Deflate/DeflateStream.cs
src/SharpCompress/Compressors/Deflate/ZlibStream.cs
src/SharpCompress/Compressors/LZMA/Bcj2DecoderStream.cs
src/SharpCompress/Compressors/LZMA/LZipStream.cs
src/SharpCompress/Compressors/Xz/Filters/Lzma2Filter.cs
src/SharpCompress/Crypto/Crc32Stream.cs
src/SharpCompress/IO/CountingWritableSubStream.cs
src/SharpCompress/IO/ListeningStream.cs
src/SharpCompress/IO/NonDisposingStream.cs
src/SharpCompress/IO/ReadOnlySubStream.cs
tests/SharpCompress.Test/ForwardOnlyStream.cs
tests/SharpCompress.Test/Zip/Zip64Tests.cs

`NonDisposingStream` and `ReadOnlySubStream` should implement `ReadByte`: currently they don't, and [the default `Stream` implementation allocates a new one-byte buffer each time](https://source.dot.net/#System.Private.CoreLib/src/System/IO/Stream.cs,757).
`Stream.ReadByte()` is used extensively by the LZMA decoder. With this simple change, I get a ~16-17% speed improvement on my machine while extracting all files in a 43MB LZMA-compressed zip file, and total memory allocations are cut by 1GB!
In the same fashion, I've also overridden `CountingWritableSubStream.WriteByte` to improve encoding. The speed results are marginal (2-3% improvement) since the encoding algorithm takes most of the CPU time, but they exist. Additional, memory traffic is also cut by a fair margin.
I've also …

Implemented ReadByte/WriteByte on streams to improve performance

---

src/SharpCompress/Common/Rar/Headers/FileHeader.cs

This will set IsEncrypted to false unless there is a file encryption header.
IsEncrypted is currently set to HasFlag(FileFlagsV4.PASSWORD) which is the same as HasFlag(FileFlagsV5.HAS_CRC32)

Correctly set IsEncrypted for entries in Rar5.

---

src/SharpCompress/Common/Zip/StreamingZipHeaderFactory.cs
src/SharpCompress/Common/Zip/ZipHeaderFactory.cs

`ReaderFactory.Open()` calls `ZipArchive.IsZipFile()` to determine if the stream is a zip archive, which calls into `ZipHeaderFactory.ReadHeader()`, which throws a `NotSupportedException` when the bytes do not match a valid header.
To be clear, this exception is caught and `IsZipFile()` returns `false`, but when called in a hot-path, these exceptions can become expensive.
To address this issue, `ReadHeader` now returns `null` in the default cause instead of throwing. All callsites were already checking for and handling `null`, so no behavior should change.

Avoid throwing NotSupportedException in ReaderFactory hot path

---

build.cake
tests/SharpCompress.Test/ArchiveTests.cs
tests/SharpCompress.Test/GZip/GZipArchiveTests.cs
tests/SharpCompress.Test/GZip/GZipWriterTests.cs
tests/SharpCompress.Test/Rar/RarArchiveTests.cs
tests/SharpCompress.Test/Rar/RarHeaderFactoryTest.cs
tests/SharpCompress.Test/Rar/RarReaderTests.cs
tests/SharpCompress.Test/ReaderTests.cs
tests/SharpCompress.Test/Tar/TarArchiveTests.cs
tests/SharpCompress.Test/Tar/TarReaderTests.cs
tests/SharpCompress.Test/TestBase.cs
tests/SharpCompress.Test/WriterTests.cs
tests/SharpCompress.Test/Zip/Zip64Tests.cs
tests/SharpCompress.Test/Zip/ZipArchiveTests.cs
tests/SharpCompress.Test/Zip/ZipReaderTests.cs

Fix two problems with the test harness
1. Give each test its own unique scratch space to prevent conflicts between tests
As part of having a unique scratch space, we can remove the `ResetScratch()` method and make the tests simpler and more resilient.
2. Avoid leaking file handles by forcing a garbage collection prior to cleanup for each test

Fix and re-enable tests

---

src/SharpCompress/Common/Zip/SeekableZipHeaderFactory.cs
tests/SharpCompress.Test/Zip/ZipArchiveTests.cs

(Related to #290)
Looking at the code, it looks to me like ZipArchive.LoadEntries already contains support for populating the ZipVolume Comment field from the DirectoryEndHeader, but that doesn't get hit because SeekableZipHeaderFactory.ReadSeekableHeader never seems to return the DirectoryEndHeader, it just breaks when there are no more DirectoryEntryHeaders.
This change changes ReadSeekableHeader to return the DirectoryEndHeader, such that the volume comment is populated.
(i'm trying to work out how this stuff works as i go along, and i'm not quite sure how all the cases for returning/breaking in ReadSeekableHeader should ne handled, but the test case suggests that the simple case of getting the archive header works.)

Changes to populate ZipArchive.ZipVolumne.Comment

---

src/SharpCompress/Writers/Tar/TarWriterOptions.cs

ArchiveEncoding can now be properly used in e.g. TarHeader.

Fix: ArchiveEncoding was ignored in TarWriterOptions

---

src/SharpCompress/Writers/Zip/ZipCentralDirectoryEntry.cs
src/SharpCompress/Writers/Zip/ZipWriter.cs

To improve compatibility with older ZIP clients I've modified the directory headers to write the corresponding 32 bit values if values still fit in 32 bits (this will allow them to read as if it's a ZIP32, and able to completely ignore the extra ZIP64 fields in ZIP headers if the decompressed size <= 32 bits)
Another problem fixed in order not to trip up 7-zip/WinRAR, zero byte files need to have compression value 0 (STORED). Now with zero byte files in the archive they will validate correctly.
I've tested these changes on WinRAR, 7-zip and windows explorer .zip (Windows 10 RS5), and using the latest changes don't get any complaints anymore extracting ZIP/ZIP64.

Various fixes for ZIP64 writer (zero byte entries, 32 bit where supported)

---

src/SharpCompress/Writers/Zip/ZipCentralDirectoryEntry.cs

Sorry Adam, while testing some bigger ZIP64 files I found a case where some archive tools don't accept having just 0xFFFFFFFF only for relative offset. This should fix that by also forcing it for compressed/decompressed size to make sure they read everything from the ZIP64 directory record when anything goes over uint32 max for that specific entry.
(according to the spec it's allowed - so technically the commit before was not wrong, but it's probably better to be on the safe side:
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
4.4.16 relative offset of local header: (4 bytes)
This is the offset from the start of the first disk on
which this file appears, to where the local header SHOULD
be found.  If an archive is in ZIP64 format and the value
in this field is 0xFFFFFFFF, the …

Fix for clients failing on just having a 64 bit offset in ZIP64

---

src/SharpCompress/Common/ExtractionOptions.cs

Hi 
I changed the default implementation for writing symbolic links to emit a warning instead of throwing an exception for this [issue](https://github.com/adamhathcock/sharpcompress/issues/464). 
Not sure how this runs for performance. 
Another thing we could try is to create platform specific commands that call out to a shell command for the various platforms. 
Something like:
```csharp
if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) {
ShellCommands.Exec($"mklink /H {source} {target}")
} else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX)) {
ShellCommands.Exec($"ln -s {target} {source}")
} else if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) {
ShellCommands.Exec($"ln -s {target} {source}")
}
```

Added default implementation with warning for symbolic links

---

src/SharpCompress/Common/Tar/TarFilePart.cs
src/SharpCompress/Common/Tar/TarReadOnlySubStream.cs
tests/SharpCompress.Test/Tar/TarArchiveTests.cs

While enumerating the entries of a tar file and writing their contents
to disk using TarArchive, it was discovered TarArchive was not properly
discarding padding bytes in the last block of each entry. TarArchive was
sometimes able to recover depending on the number of padding bytes due
to the logic it uses to find the next entry header, but not always.
TarArchive was changed to use TarReadOnlySubStream when opening entries
and TarReadOnlySubstream was changed to ensure all an entry's blocks are
read when it is being disposed.
Fixes adamhathcock/sharpcompress#524

Ensure TarArchive enumerates all entries

---

src/SharpCompress/IO/NonDisposingStream.cs
src/SharpCompress/Polyfills/StreamExtensions.cs
tests/SharpCompress.Test/SharpCompress.Test.csproj
tests/SharpCompress.Test/Tar/TarReaderTests.cs
tests/SharpCompress.Test/Zip/ZipWriterTests.cs

This PR enables test coverage for .NET 4.6.1 and fixes an error introduced in my last PR.
There are 5 failing ZipWriter tests that are currently failing that are conditionally excluded. These have been failing for a while (before any recent PRs) and should be addressed in a separate PR.

Enable test coverage for net461 and fix regression

---

src/SharpCompress/IO/RewindableStream.cs
src/SharpCompress/SharpCompress.csproj
tests/SharpCompress.Test/GZip/GZipReaderTests.cs

for https://github.com/adamhathcock/sharpcompress/issues/562

Fix Rewindable stream Length and add GZip Reader tests

---

src/SharpCompress/Common/Zip/Headers/LocalEntryHeaderExtraFactory.cs

Fix for Issue #566 - Zip64 - 0 Size on Entry > 4GiB
This is my first PR. If I've done anything incorrectly please point it out and I'll take it on board.
I've tested this on many archives.

Zip64 Header and Size fix

---

src/SharpCompress/Archives/Rar/RarArchive.cs
src/SharpCompress/Archives/Rar/RarArchiveEntry.cs
src/SharpCompress/Archives/Rar/RarArchiveEntryFactory.cs
src/SharpCompress/Common/Rar/Headers/FileHeader.cs
src/SharpCompress/Readers/ReaderOptions.cs

I have been doing some work involving processing incomplete RAR files and file sets, and I had to make a few tweaks to make SharpCompress ok with trying to read the partial data and figured they useful enough to share.

Improve how missing parts are handled

---

src/SharpCompress/Writers/Zip/ZipWriter.cs

Zip64 requires version 4.5
Number of disks is 4 bytes and not 8
#540

Proposal fixing Extra bytes written when setting zip64

---

src/SharpCompress/Polyfills/StreamExtensions.cs
src/SharpCompress/Polyfills/StringExtensions.cs

Do not place extension classes in common namespace, as the extension methods might conflict with the same counterpart (same name, same signature) from another separated namespace.

Do not place extension classes in common namespace

---

src/SharpCompress/Common/Zip/SeekableZipHeaderFactory.cs
tests/SharpCompress.Test/Zip/ZipArchiveTests.cs

In our workflow it may happen that we attempt to access zip files that don't actually have any content. Until earlier versions that worked, but with the last implementation of SeekableZipHeaderFactory it fails. I suggest parsing the entire stream instead of skipping the oecd region. Respective unit test is added, too.
If you accept the changes, please publish a new nuget package.
Best regards

Allowing to seek empty zip files

---

src/SharpCompress/Writers/Tar/TarWriter.cs

For large files, due to how the padding was calculated an additional 512 bytes was added. I noticed this while archiving a file (size 11721453867 bytes, i.e. 11gb, roughly) and 725 null bytes were added as padding, instead of 213. This new method calculates large sizes correctly (and is faster!).

Bugfix for TarWriter - too much padding in large files

---

.github/workflows/dotnetcore.yml
build/build.csproj
global.json
src/SharpCompress/Common/ExtractionMethods.cs
src/SharpCompress/SharpCompress.csproj
tests/SharpCompress.Test/SharpCompress.Test.csproj

Also check for trailing slash and add if necessary

Ensure destination directory exists.

---

src/SharpCompress/Algorithms/Alder32.cs
src/SharpCompress/Common/ArchiveEncoding.cs
src/SharpCompress/Compressors/BZip2/BZip2Stream.cs
src/SharpCompress/Compressors/LZMA/LZipStream.cs
src/SharpCompress/Crypto/Crc32Stream.cs
src/SharpCompress/IO/NonDisposingStream.cs
src/SharpCompress/Polyfills/StreamExtensions.cs
src/SharpCompress/Polyfills/StringExtensions.cs
src/SharpCompress/SharpCompress.csproj

.NET has a few known issues for libraries that depend on `System.*` and only ship a `netstandard2.0` target
1. .NET has different assembly versions for `netstandard2.0` versus `net461` (see #591). Unless assembly binding redirects are carefully applied, there will be runtime errors.
2. The build output will have tons of "façade" assemblies (see the blogpost in reference 2)
Given the two issues above official guidance is (see reference 1)
> ✔️ CONSIDER adding a target for net461 when you're offering a netstandard2.0 target.
> 
> Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2. You can improve the experience for developers that are still on .NET Framework 4.6.1 - 4.7.1 by offering them a binary that is built for .NET Framework 4.6.1. …

Add net461 target to clean up issues with system.* nuget dependencies

---

src/SharpCompress/SharpCompress.csproj

Some licensing tools I use (Snyk) were failing to identify SharpCompress' MIT license as it's not bundled into the Nuget package. This bundles LICENSE.txt in the root of the repo into the package following guidance [here](https://docs.microsoft.com/en-gb/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file).
Before:
After:
Could alternatively include an SPDX license expression but this [wouldn't include specific wording for the author's copyright](https://licenses.nuget.org/MIT)
```
<PropertyGroup>
<PackageLicenseExpression>MIT</PackageLicenseExpression>
</PropertyGroup>
```

Include license in nuget package

---

src/SharpCompress/IO/SourceStream.cs
src/SharpCompress/Utility.cs

Encountered a position counting bug, it add the stream size even if the stream is not switched.
This should fix it and I also removed the workaround I had.

SourceStream Position counting bug fix

---

src/SharpCompress/SharpCompress.csproj

This makes it easier to validate the license used as it can be automatically checked by tools.

Use PackageLicenseExpression instead of PackageLicenseFile

---

src/SharpCompress/Compressors/Xz/Filters/BlockFilter.cs

This fixes `System.MissingMethodException` when using XZ decompressor in NativeAOT.
1. create new console project and set TargetFramework to net7.0
2. add SharpCompress package(this issue was investigated in 0.32.2)
3. edit cs to following reproducible code
4. publish with NativeAOT(and rid) option
5. create xz archive file
6. execute published executable file
```csharp
using SharpCompress.Compressors.Xz;
using(var istm = File.OpenRead("test.xz"))
using(var xstm = new XZStream(istm))
using(var ostm = File.Create("test.txt"))
{
xstm.CopyTo(ostm);
}
```
"test.txt" is created and written decompressed result
System.MissingMethodException is thrown.
```
Unhandled Exception: System.MissingMethodException: No parameterless constructor defined for type …
```

replace Activator.CreateInstance to Func for avoiding error in NativeAOT

---

src/SharpCompress/Common/Tar/TarEntry.cs
tests/SharpCompress.Test/Tar/TarArchiveTests.cs
tests/SharpCompress.Test/Tar/TarReaderTests.cs

Guess this would be one way to handle #736

Check for broken file #736

---

src/SharpCompress/Common/Rar/RarCryptoWrapper.cs
src/SharpCompress/Readers/AbstractReader.cs
src/SharpCompress/Readers/Rar/NonSeekableStreamFilePart.cs
tests/SharpCompress.Test/Rar/RarReaderTests.cs

Proposal for #743 , where the rar archive headers are not encrypted but the files are.
@yousa123080 , you can try this and see if it helps your case.

Skip if we know the size, set blank password if not set for rar

---

src/SharpCompress/Archives/IArchiveExtensions.cs

As mentioned in #728 (and I believe some other issues), the `IArchive.WriteToDirectory(...)` extension method can be very slow for `.7z` files. This extension utilized `IArchive.ExtractAllEntries()` and `IReader` so is fast for .7z files.
Being async has nothing to do with the performance, rather, it's because I use this extension method from an async method and need it to perform the long-running work asynchronously. Ideally `IArchive.ExtractAllEntries()` and `IReader.WriteEntryTo(Stream)` would be async as well and then the whole Task.Run wouldn't be needed and then it would make more sense to be async.
It currently doesn't support `ExtractionOptions` or reporting progress through `IArchive`'s events (although it does report progress through a callback). But, it works great as-is for my …

Add fast `ExtractToDirectoryAsync` extension method on `IArchive`

---

src/SharpCompress/Common/ReaderCancelledException.cs
src/SharpCompress/Readers/AbstractReader.cs

I needed a way to gracefully handle a cancellation. It would have been much easier to catch a specific type of exception instead of relying on the message of `InvalidOperationException`.
So, here you go!

Throw ReaderCancelledException on reader cancelled

---

src/SharpCompress/SharpCompress.csproj

As title mentions. Strong name signing was disabled via 92df1ec in a large merge adding zstd support. 
Due to [this comment from @adamhathcock](https://github.com/adamhathcock/sharpcompress/issues/764#issuecomment-1723218890), I believe this was just a mistake. So here is a PR which resolves the issue. 
Accepting this PR will fix #764

Revert change disabling strong name signing in 92df1ec

---

src/SharpCompress/Writers/Zip/ZipWriter.cs

0xFFFF will be written to the EOCD to signal to use the ZIP64 CentralDirectory record when the number of files is 65,535 or more. Fixes #791

ZipWriter: Write correct EOCD record when more than 65,535 files

---

src/SharpCompress/Common/Rar/RarCryptoWrapper.cs
src/SharpCompress/Common/SevenZip/ArchiveReader.cs
src/SharpCompress/Common/Tar/TarReadOnlySubStream.cs
src/SharpCompress/Common/Zip/PkwareTraditionalCryptoStream.cs
src/SharpCompress/Common/Zip/WinzipAesCryptoStream.cs
src/SharpCompress/Compressors/Filters/BCJ2Filter.cs
src/SharpCompress/Compressors/Filters/Filter.cs
src/SharpCompress/Compressors/LZMA/DecoderStream.cs
src/SharpCompress/Compressors/Rar/MultiVolumeReadOnlyStream.cs
src/SharpCompress/Compressors/Xz/ReadOnlyStream.cs
src/SharpCompress/IO/BufferedSubStream.cs
src/SharpCompress/IO/DataDescriptorStream.cs
src/SharpCompress/IO/ReadOnlySubStream.cs
src/SharpCompress/IO/RewindableStream.cs
tests/SharpCompress.Test/Mocks/FlushOnDisposeStream.cs
tests/SharpCompress.Test/Mocks/ForwardOnlyStream.cs

#771 , remove throwing NotSupported for flush

Issue 771, remove throw on flush for readonly streams

---

src/SharpCompress/IO/DataDescriptorStream.cs

#795
We get out of sync after reporting the wrong size, mess up the 64 bit detection later

Fix reporting size / position

---

src/SharpCompress/Common/Zip/Headers/DirectoryEntryHeader.cs
src/SharpCompress/Common/Zip/Headers/LocalEntryHeader.cs
src/SharpCompress/Common/Zip/Headers/ZipFileEntry.cs
src/SharpCompress/Common/Zip/PkwareTraditionalEncryptionData.cs

The last modified time used for zip decryption validation must be the one from the basic header. If UnixTimeExtraFields are present, the previous implementation was attempting to verify against that value instead.
Fixed #804

Zip: Use last modified time from basic header when validating zip decryption

---

src/SharpCompress/Common/Rar/Headers/FileHeader.cs
src/SharpCompress/Common/Rar/Headers/Flags.cs
src/SharpCompress/Common/Rar/RarEntry.cs
src/SharpCompress/Compressors/Rar/RarStream.cs
src/SharpCompress/Readers/Rar/RarReader.cs

NOTE: api user should skip entries where RarEntry.IsRedir is true and not call OpenEntryStream()

rar5 read FHEXTRA_REDIR and expose via RarEntry

---

src/SharpCompress/BufferPool.cs
src/SharpCompress/Compressors/Rar/RarStream.cs
src/SharpCompress/Compressors/Rar/UnpackV2017/Unpack.cs
src/SharpCompress/Compressors/Rar/UnpackV2017/Unpack.unpack20_cpp.cs
src/SharpCompress/Compressors/Rar/UnpackV2017/Unpack.unpack50_cpp.cs
src/SharpCompress/Compressors/Rar/UnpackV2017/Unpack.unpack_cpp.cs

use ArrayPool for stream buffer
use stackalloc for methods on file decompression code path

rar5 improve memory usage

---

README.md

API Documentation was changed to 'https://dndocs.com/'  and url need to be updated to point to new location.
Domain 'www.robiniadocs.com' will be removed.

Update README.md - Change API Docs to DNDocs

---

src/SharpCompress/Archives/GZip/GZipArchive.cs
tests/SharpCompress.Test/GZip/GZipArchiveTests.cs

Fix gzip archives having a `Type` of `ArchiveType.Tar` instead of `ArchiveType.Gzip`

---

src/SharpCompress/Common/Zip/StreamingZipHeaderFactory.cs
src/SharpCompress/Common/Zip/ZipHeaderFactory.cs

When a ZIP64 entry is extracted from an archive, the header for the next entry is read out of order. This commit reads the header again, then resets the position of the RewindableStream back to the beginning of the entry, just after the 4 byte header signature. This ensures the correct header signature data and reader (in the correct position) are fed to ReadHeader. Previously this would have read the data at an incorrect offset and would not yield a viable ZipHeader.
I haven't done extensive testing with this nor did I write any automated tests.

Fixed extractions after first ZIP64 entry is read from stream

---

src/SharpCompress/Archives/IArchiveExtensions.cs

Fixes: #851 
This creates empty directories without skipping them when using ExtractToDirectory.

Fix for missing empty directories when using ExtractToDirectory

---

src/SharpCompress/Common/ExtractionMethods.cs
src/SharpCompress/Utility.cs

Add a method to replace invalid characters in file names with underscores during file extraction. This prevents errors related to invalid file names.

Fix #858 - Replaces invalid filename characters

---

src/SharpCompress/Archives/ArchiveFactory.cs

- closes #870
By resetting the stream position after the archive check, the stream position will be restored to its original value after the method returns.

Restore stream position in ArchiveFactory.IsArchive

---

src/SharpCompress/Common/Zip/Headers/LocalEntryHeaderExtraFactory.cs
src/SharpCompress/Common/Zip/ZipEntry.cs

Parsing the times in the zip headers worked, but the flag check was wrong, so only modified time was ever parsed. Corrected this in a more readable way.
Also stopped exceptions being thrown if there was an issue during this header parsing, returning null values instead.
Remarks have been added to highlight that they return UTC `DateTime`'s, rather than `LastModifiedTime` which returns a local `DateTime`.

Fixed bug in zip time header flags

---

src/SharpCompress/Common/Zip/SeekableZipFilePart.cs
src/SharpCompress/Common/Zip/SeekableZipHeaderFactory.cs
tests/SharpCompress.Test/Zip/ZipArchiveTests.cs

- closes #88
See the included test for how this issue surfaces. The missing fields in the local header will now be set from the directory header if the `UsePostDataDescriptor` bit is set in the local header's flags.

Fix zip entry handling for entries with data descriptors

---

src/SharpCompress/Compressors/Rar/UnpackV1/Unpack20.cs

Fix for #216 which I had recently encountered too. This is a small change to CopyString20(), after making it I noticed the same condition already existed in CopyString(). So I'm confident it's good.
The fix has since been tested on over 300 archives that were failing to decompress with the latest SharpCompress and over 250ish were fixed.

Fix for Rar4 v20 compression.

---

src/SharpCompress/Compressors/Rar/UnpackV1/Unpack.cs
src/SharpCompress/Compressors/Rar/UnpackV2017/Unpack.unpack50_cpp.cs

- closes #890
This was an interesting one to track down. Basically, when `UnpWriteData` is called with a size of `0`, it must call `writeStream.Write` even if `destUnpSize` is 0 to ensure that `Suspended` is set to false.
The same condition change must be done here: https://github.com/adamhathcock/sharpcompress/blob/94789ce455cf88cbe0636abc0071c1c03d4a2ebf/src/SharpCompress/Compressors/Rar/UnpackV1/Unpack.cs#L266 
to make sure that the code passes over both `if (destUnpSize < 0)` and `if (suspended)` conditions and continues below.
While investigating this bug I found some other issues in the rarVM code, but I'm not sure how to test them and whether that code is even still used nowadays.
TODO: Find some example archive that shows this bug that isn't 40MB and add a test case for it.

Fix condition in rar v3 code

---

src/SharpCompress/Compressors/LZMA/LZ/LzOutWindow.cs
src/SharpCompress/Compressors/LZMA/LzmaStream.cs

Similar to #897, this improves performance and reduces memory allocations when reading certain 7-zip files.
Using the .7z file from https://github.com/adamhathcock/sharpcompress/issues/399#issuecomment-405028725, I measured a speedup in reading / skipping the entire .7z file from ~23 seconds to ~18 seconds, and memory allocations dropped by ~8.5GB.

Implement ReadByte for LzmaStream and LzOutWindow

---

src/SharpCompress/IO/BufferedSubStream.cs

I noticed absurd memory allocations when decompressing 7-zip files and tracked it down to `BufferedSubStream` not overriding `ReadByte`.
From the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-9.0): `The default implementations of ReadByte() and WriteByte(Byte) create a new single-element byte array, and then call your implementations of Read(Byte[], Int32, Int32) and Write(Byte[], Int32, Int32). When you derive from Stream, we recommend that you override these methods to access your internal buffer, if you have one, for substantially better performance.`
Testing with a ~300MB (compressed size) 7-zip file, I noticed an improvement in decompression speed from ~32 seconds to ~27 seconds and a reduction in memory allocations from ~7GB to ~100MB.

Implement ReadByte for BufferedSubStream

---

src/SharpCompress/Archives/ArchiveFactory.cs
src/SharpCompress/Archives/IArchiveExtensions.cs

- closes #710 and possibly some other related ones
For extracting files from solid archives calling `ExtractAllEntries` is required to get acceptable extraction performance and should therefore always be called.
Clearly people are not aware of this function, and the base library not using it is not helping. Perhaps it should be mentioned in the `USAGE.md`?

make WriteToDirectory functions use ExtractAllEntries

---

src/SharpCompress/Compressors/LZMA/RangeCoder/RangeCoder.cs
src/SharpCompress/Compressors/LZMA/RangeCoder/RangeCoderBit.cs

I noticed this duplicated bit of logic inside the range decoder. Turns out, there's a helper function called `Normalize2` that does the exact same thing and was never even called. This quirk came all the way from the original LZMA C# SDK it seems. I can see why, as with .NET Framework 4.8, attempting to use the helper function results in performance degradation, so someone manually inlined it. But that's not even necessary, as `[MethodImpl(MethodImplOptions.AggressiveInlining)]` can be used to achieve the same performance.
But the more interesting part, hence this PR, is that newer JITs (tested with .NET 8.0) don't like the manually inlined version of the code as much; when calling `Normalize2` instead, it seems to get inlined either way (even without the attribute that we put as a hint …

Optimize LZMA range decoder

---

USAGE.md

I've modified the "extract all files" example to use `IReader.ExtractAllEntries`. As per the added comment this must be done for solid archives and probably has better performance compared to iterating over entries in non-sequential order for other archives too.
I've added a new example for iterating over entries that doesn't extract them.

Update USAGE.md to remove problematic extraction example

---

src/SharpCompress/IO/BufferedSubStream.cs

In `BufferedSubStream`, by changing what `BytesLeftToRead` and `_cacheLength` track, we can simplify the work to be done when reading a byte. `BytesLeftToRead` now tracks the amount of completely unread/uncached data, and `_cacheLength` tracks the total cache length including the consumed portion. Then  we only need to update the cache offset when reading a byte. It also moves the logic to refresh the cache into its own method. Interestingly, only about half of the performance increase comes from simplifying the variable usage. The other half comes from moving out the cache refresh logic, presumably because it makes the `ReadByte` method small enough for callers to inline.
Core i7-6700k (1.7% reduction):
| Method | Mean    | Error    | StdDev   |
|------- |--------:|---------:|---------:| …

Optimize BufferedSubStream.ReadByte

---

src/SharpCompress/IO/BufferedSubStream.cs

Fixes regression introduced in #912. Most of my test archives didn't trigger this code path so I didn't notice until now.

Fix regression with BufferedSubStream calculation

---

src/SharpCompress/Archives/Rar/RarArchive.cs
src/SharpCompress/Readers/AbstractReader.cs
tests/SharpCompress.Test/Rar/RarReaderTests.cs

- closes #915.
One side-effect of the changes here is that *skipping over encrypted entries for which the password is not known in a multipart rar file using the reader interface* no longer works.
However *reading* those entries does not work because it isn't currently implemented, and the skipping was bad as well because it would fail to skip all file parts and returned after skipping the first part only, so I think it is fair to remove this functionality.
It could be implemented properly but I think it would take some effort to extract the needed information and perhaps need additional interface methods.

Implement multipart rar handling for ExtractAllEntries

---

src/SharpCompress/Common/Volume.cs

- closes #920
If the `ReaderOptions` has `LeaveStreamOpen` set (which is set to true by default), the stream used to report a volume's `FileName` was a `NonDisposingStream` instead of the originally passed in stream, which never worked.

Fix volume FileName property potentially missing
