adamhathcock/sharpcompress

SharpCompress.Test/SharpCompress.Test.csproj, SharpCompress.Test/TestBase.cs, SharpCompress/AssemblyInfo.cs
1) disabled requirement of signature
2) added runtime discovery of folder with archives
changes by this commit are already present in 13ef1c3, but they weren't merged into master
=> Improved testability

SharpCompress.Test/SharpCompress.Test.csproj, SharpCompress.Test/TestBase.cs, SharpCompress/AssemblyInfo.cs, SharpCompress/Common/Zip/Headers/ZipFileEntry.cs
Fixed running out of bounds of array. (Tests with zipx in it cause fail there).
P.S. merge #56 first
=> Zip file entry load extra array overflow fix

SharpCompress/Archive/IArchiveEntry.Extensions.cs, SharpCompress/Common/ExtractOptions.cs
Check PreserveFileTime when file times are initialized.
=> Use enum as flag correctly

SharpCompress/Archive/Zip/ZipArchive.cs, SharpCompress/Common/Zip/SeekableZipHeaderFactory.cs, SharpCompress/Common/Zip/StreamingZipHeaderFactory.cs, SharpCompress/Common/Zip/ZipHeaderFactory.cs, SharpCompress/Compressor/Deflate/DeflateManager.cs
- Fixed non-compilable statements in DelfateManager
- Eliminated "throw - catch all" logic in ZipArchive (performance issue)
- ZipArchive with comments handling
=> Non-compilable statements + zip archive handling  

SharpCompress/Utility.cs
Fix of this bug:
https://github.com/adamhathcock/sharpcompress/issues/126
=> Fixed bug triggered by incomplete rar file.

src/SharpCompress/Common/SevenZip/ArchiveReader.cs
The high bits may contain posix file attributes when the archive was written by certain third party 7z implementations. These must be removed before we can interpret the attributes as windows (or .NET) file attributes.
This was discovered in issue #73 and should be fixed, even though it is not the main problem in that issue.
=> Ignore unofficial extension of file attributes.

src/SharpCompress/Archives/SevenZip/SevenZipArchive.cs
=> Removed restriction on 7zip file entries

src/SharpCompress/IO/RewindableStream.cs
https://github.com/dotnet/corefx/issues/20676
https://github.com/adamhathcock/sharpcompress/issues/255
I guess I should do this for more streams.
=> Bug on Windows on .NET Core fix

FORMATS.md, README.md, USAGE.md
Hello! This PR was requested from [PrettierCI Instant](https://www.prettierci.com/instant). We've run [Prettier](https://prettier.io/) on the repo and submitted the diff.
If this is the first time Prettier has been run against your repo, there might be some unnecessary or irrelevant changes - if you're interested, you can configure specific files to ignore and other behaviors via [Prettier configuration](https://prettier.io/docs/en/options.html).
To limit pull request overload, this will be the only PR from PrettierCI Instant. If you're interested in running Prettier continually on your repo (including status checks and automated commits), check out the full [PrettierCI](https://www.prettierci.com).
=> PrettierCI master Sync

.gitignore, src/SharpCompress/Common/EntryStream.cs
Covers https://github.com/adamhathcock/sharpcompress/issues/370
=> Expose stream length.  Clean up entry stream

src/SharpCompress/Common/ArchiveEncoding.cs
Fixes https://github.com/adamhathcock/sharpcompress/issues/380
=> Allow forced encoding to override default encoding

.circleci/config.yml, src/SharpCompress/Archives/IArchiveEntryExtensions.cs, src/SharpCompress/Archives/IArchiveExtensions.cs, src/SharpCompress/Common/ExtractionMethods.cs, src/SharpCompress/Common/ExtractionOptions.cs, src/SharpCompress/Readers/IReaderExtensions.cs
Fixes https://github.com/adamhathcock/sharpcompress/issues/394
=> Zip slip for Readers

src/SharpCompress/Writers/IWriterExtensions.cs
=> file search support linq Pattern

src/SharpCompress/Archives/GZip/GZipArchive.cs, src/SharpCompress/Common/SevenZip/ArchiveReader.cs, src/SharpCompress/Common/Zip/Headers/LocalEntryHeaderExtraFactory.cs, src/SharpCompress/Compressors/BZip2/BZip2Stream.cs, src/SharpCompress/Compressors/Deflate/ZlibBaseStream.cs, src/SharpCompress/Compressors/LZMA/LZipStream.cs, src/SharpCompress/Crypto/Crc32Stream.cs, src/SharpCompress/Crypto/RijndaelEngine.cs, src/SharpCompress/IO/NonDisposingStream.cs, src/SharpCompress/Polyfills/StreamExtensions.cs, src/SharpCompress/Utility.cs, src/SharpCompress/Writers/Zip/ZipWriter.cs
This PR polyfills Stream.Write(ReadOnlySpan<byte> buffer) on .NET framework and eliminates a few allocations.
=> Improve code quality v2

src/SharpCompress/Common/GZip/GZipFilePart.cs, src/SharpCompress/Common/Rar/RarRijndael.cs, src/SharpCompress/Common/SevenZip/CMethodId.cs, src/SharpCompress/Common/Tar/Headers/TarHeader.cs, src/SharpCompress/Compressors/ADC/ADCBase.cs, src/SharpCompress/Compressors/BZip2/CBZip2InputStream.cs, src/SharpCompress/Compressors/BZip2/CBZip2OutputStream.cs, src/SharpCompress/Compressors/Deflate/CRC32.cs, src/SharpCompress/Compressors/Deflate/ZlibBaseStream.cs, src/SharpCompress/Compressors/Deflate64/FastEncoderStatus.cs, src/SharpCompress/Compressors/Deflate64/HuffmanTree.cs, src/SharpCompress/Compressors/LZMA/LZipStream.cs, src/SharpCompress/Compressors/Rar/UnpackV1/UnpackUtility.cs, src/SharpCompress/Compressors/Rar/UnpackV2017/unpack_hpp.cs, src/SharpCompress/Crypto/IBlockCipher.cs, src/SharpCompress/Crypto/RijndaelEngine.cs, src/SharpCompress/Polyfills/StreamExtensions.cs
This PR eliminates various allocations by utilizing the stack to allocate short lived arrays.
=> Improve CQ3

src/SharpCompress/Archives/AbstractArchive.cs, src/SharpCompress/Archives/AbstractWritableArchive.cs, src/SharpCompress/Archives/ArchiveFactory.cs, src/SharpCompress/Archives/Rar/RarArchiveVolumeFactory.cs, src/SharpCompress/Common/ArchiveEncoding.cs, src/SharpCompress/Common/ExtractionMethods.cs, src/SharpCompress/Common/Rar/Headers/NewSubHeaderType.cs, src/SharpCompress/Common/SevenZip/ArchiveReader.cs, src/SharpCompress/Common/SevenZip/CMethodId.cs, src/SharpCompress/Common/Zip/Headers/ZipFileEntry.cs, src/SharpCompress/Compressors/BZip2/BZip2Stream.cs, src/SharpCompress/Compressors/Deflate/GZipStream.cs, src/SharpCompress/Compressors/LZMA/AesDecoderStream.cs, src/SharpCompress/Compressors/LZMA/LZipStream.cs, src/SharpCompress/Compressors/Xz/Filters/BlockFilter.cs, src/SharpCompress/Crypto/Crc32Stream.cs, src/SharpCompress/IO/NonDisposingStream.cs, src/SharpCompress/Polyfills/StreamExtensions.cs, src/SharpCompress/Polyfills/StringExtensions.cs, src/SharpCompress/SharpCompress.csproj, tests/SharpCompress.Test/SharpCompress.Test.csproj
A handful of tiny cleanups and precursor work to introduce hardware accelerated checksum algorithms.
=> Improve Code Quality 3

src/SharpCompress/Algorithms/Alder32.cs, src/SharpCompress/SharpCompress.csproj, tests/SharpCompress.Test/SharpCompress.Test.csproj, tests/SharpCompress.Test/Streams/ZlibBaseStreamTests.cs
Fix for https://github.com/adamhathcock/sharpcompress/issues/617
=> Add test and probable fix for Issue 617

src/SharpCompress/Common/Tar/Headers/TarHeader.cs, src/SharpCompress/Common/Tar/TarEntry.cs
=> Tar file mode, user and group

src/SharpCompress/Archives/GZip/GZipWritableArchiveEntry.cs, src/SharpCompress/Archives/Tar/TarWritableArchiveEntry.cs, src/SharpCompress/Archives/Zip/ZipWritableArchiveEntry.cs, src/SharpCompress/Common/Volume.cs, src/SharpCompress/Common/Zip/StreamingZipFilePart.cs, src/SharpCompress/Common/Zip/ZipFilePart.cs, src/SharpCompress/Compressors/Xz/XZFooter.cs, src/SharpCompress/Compressors/Xz/XZHeader.cs, src/SharpCompress/Compressors/Xz/XZIndex.cs, src/SharpCompress/IO/NonDisposingStream.cs, src/SharpCompress/Readers/ReaderFactory.cs, src/SharpCompress/Writers/GZip/GZipWriter.cs, src/SharpCompress/Writers/Tar/TarWriter.cs, src/SharpCompress/Writers/Zip/ZipWriter.cs, tests/SharpCompress.Test/ArchiveTests.cs, tests/SharpCompress.Test/ReaderTests.cs, tests/SharpCompress.Test/Streams/ZlibBaseStreamTests.cs, tests/SharpCompress.Test/WriterTests.cs, tests/SharpCompress.Test/Zip/ZipReaderTests.cs
Suppresses the creation of a `NonDisposingStream` which wrappes another `NonDisposingStream` with same settings
=> Suppress nested NonDisposingStream

src/SharpCompress/Compressors/LZMA/ICoder.cs, src/SharpCompress/Compressors/LZMA/LzmaEncoder.cs, src/SharpCompress/Compressors/LZMA/LzmaEncoderProperties.cs, src/SharpCompress/Compressors/LZMA/LzmaStream.cs, tests/SharpCompress.Test/Streams/LzmaStreamTests.cs
* Encapsulation and Immutability for LzmaEncoderProperties
* LzmaEncoderProperties.Default static property
* Encoding tests for LzmaStream
=> Several improvements to the LZMA Compressor

USAGE.md
Had some difficult figuring this one out, as this is so straight forward and is the simplest use case, maybe should be included at the top of the docs ?
=> Added simple example

src/SharpCompress/SharpCompress.csproj
The 0.6.1 gives my computer "Common Language Runtime detected an invalid program."
=> Update Zstd to 0.7.2

src/SharpCompress/Common/Rar/CryptKey5.cs, tests/SharpCompress.Test/ArchiveTests.cs, tests/SharpCompress.Test/Rar/RarArchiveTests.cs, tests/SharpCompress.Test/Rar/RarReaderTests.cs, tests/SharpCompress.Test/ReaderTests.cs
=> Set Empty string for Rar5 password as default

src/SharpCompress/Common/Zip/Headers/DirectoryEntryHeader.cs, src/SharpCompress/Common/Zip/Headers/LocalEntryHeader.cs, src/SharpCompress/Common/Zip/Headers/LocalEntryHeaderExtraFactory.cs
=> Add support for the UnixTimeExtraField in Zip files

src/SharpCompress/SharpCompress.csproj
Linked the root README.md to the SharpCompress src project
=> #809 Add README.md to csproj for NuGet

src/SharpCompress/Common/Tar/Headers/TarHeader.cs
=> Tar: Add processing for the LongLink header type

src/SharpCompress/Common/Rar/RarVolume.cs
Not really sure what we are doing here with the CreatePart etc, but reading the stream works for the test cases and the sample.rar that failed.
#844
=> Fix for issue #844

Directory.Packages.props, build/packages.lock.json, src/SharpCompress/SharpCompress.csproj, src/SharpCompress/packages.lock.json, tests/SharpCompress.Test/packages.lock.json
Should replace https://github.com/adamhathcock/sharpcompress/pull/862
=> Update csproj to get green marks and update deps

SharpCompress.sln.DotSettings
Some of these generate very annoying code, especially because the editorconfig disagrees with it.
=> fix DotSettings options to conform to current code style and editorconfig
